import operator
from typing import Annotated, List, TypedDict, Dict, Any
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgenticRAGState(TypedDict):
    """
    Central memory object for the Multi-Agent State Machine.
    """
    query: str
    
    # Hidden routing dictionary generated by the Orchestrator
    routing_decisions: Dict[str, bool]
    
    # Isolated Contexts
    india_context: str
    sg_context: str
    
    # Tool Execution Memory logs
    math_expressions: Annotated[List[str], operator.add]
    math_results: Annotated[List[str], operator.add]
    generated_code: Annotated[List[str], operator.add]
    
    # The conversational history and system logs
    messages: Annotated[List[BaseMessage], add_messages]
    
    # Final synthesized output
    final_answer: str